const db = require("../client");

module.exports.seedPart1 = async (req, res, next) => {
  //Questions query
  const questionsQuery = `
    INSERT INTO questions (question_name, issue_tackled) VALUES
    ('I would like to help protect the environment', 'Environmental preservation'), 
    ('I would like to understand what is the universe made of', 'Physics'), 
    ('I would like to learn how atoms and molecules interact via chemical bonds to form new chemical compounds', 'Chemistry'), 
    ('I would like to work on improving food accessibility', 'Food Accesibility'), 
    ('I would like to help cure diseases','Medicine'), 
    ('I would like to know if there are other universes', 'Understanding the universe' ), 
    ('I would like to help find affordable clean energy', 'Alternative energies'), 
    ('I would like to develop new technologies', 'New technologies'), 
    ('I would like know what the starts have to tell us about us and the universe','Astronomy'),
    ('I would like to know how different are other planets from earth', 'Planetary Science'),
    ('I would like to develop new materials to make safer, more affordable working gears', 'Materials development')
    RETURNING *;
`;
  try {
    const {rows} = await db.query(questionsQuery);
    res.status(201).json(rows)
} 
  catch (e) {
    console.log({ questionSeedError: e.message });
  }
};

module.exports.scientistHasQuestion = async (req, res, next) => {
  const shqQuery = `
    INSERT INTO scientist_has_question (scientist_id, question_id) VALUES
    (1, 1),
    (2, 1),
    (8, 1),
    (10, 1),
    (12, 2),
    (14, 2),
    (18, 2),
    (35, 2),
    (2, 3),
    (9, 3),
    (13, 3),
    (15, 3),
    (16, 3),
    (20, 3),
    (23, 3),
    (37, 3),
    (39, 3),
    (41, 3),
    (42, 3),
    (44, 3),
    (9, 4),
    (44, 4),
    (3, 5),
    (4, 5),
    (5, 5),
    (6, 5),
    (15, 5),
    (16, 5),
    (17, 5),
    (20, 5),
    (23, 5),
    (24, 5),
    (39, 5),
    (40, 5),
    (41, 5),
    (42, 5),
    (43, 5),
    (45, 5),
    (46, 5),
    (47, 5),
    (48, 5),
    (50, 5),
    (7, 6),
    (19, 6),
    (21, 6),
    (22, 6),
    (25, 6),
    (27, 6),
    (28, 6),
    (29, 6),
    (30, 6),
    (52, 6),
    (53, 6),
    (48, 7),
    (3, 8),
    (28, 8),
    (32, 8),
    (33, 8),
    (36, 8),
    (38, 8),
    (44, 8),
    (21, 9),
    (22, 9),
    (25, 9),
    (26, 9),
    (27, 9),
    (34, 10),
    (49, 10),
    (51, 10),
    (54, 10),
    (11, 11),
    (13, 11)
    RETURNING *;
`;
  try {
    const {rows} = await db.query(shqQuery);
    res.status(201).json(rows)
} 
  catch (e) {
    console.log({ shqSeedError: e.message });
  }
};


module.exports.seedPart2 = async (req, res, next) => {
     // Scientist query
    const scientistsQuery = `
      INSERT INTO scientist (first_name, 
        last_name,
        area_expertise,
        field,
        issue_tackled,
        wiki_link,
        picture) VALUES
      ('Eugenie', 'Clark', 'Ichthyologist', '{"Biology"}', '{"Environmental preservation"}', 'https://en.wikipedia.org/wiki/Eugenie_Clark',	'http://www.alertdiver.com/cdn/13649.jpg'),
      ('Susan', 'Solomon',	'Atmospheric Chemist',	'{"Chemistry"}',	'{"Environmental preservation", "Chemistry"}',	'https://en.wikipedia.org/wiki/Susan_Solomon' , 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Susan_Solomon-Desk_With_Globe.jpg/1024px-Susan_Solomon-Desk_With_Globe.jpg'),
      ('Donna Theo', 'Strickland', 'Physics, Optics, and Lasers', '{"Physics"}', '{"Medicine", "New technologies"}',	'https://en.wikipedia.org/wiki/Donna_Strickland',	'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Donna_Strickland_EM1B5760_%2846183560632%29_%28cropped%29.jpg/220px-Donna_Strickland_EM1B5760_%2846183560632%29_%28cropped%29.jpg'),
      ('Linda', 'Brown Buck', 'Biologist', '{"Biology"}', '{"Medicine"}', 'https://en.wikipedia.org/wiki/Linda_B._Buck', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Linda_Buck_2015_%28cropped%29.jpg/200px-Linda_Buck_2015_%28cropped%29.jpg'),
      ('Carol Widney', 'Greider',	'Molecular Biologist', '{"Biology"}', '{"Medicine"}', 'https://en.wikipedia.org/wiki/Carol_W._Greider', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/GREIDER_Carol_2014_-_Less_vignetting.jpg/220px-GREIDER_Carol_2014_-_Less_vignetting.jpg'),
      ('Elizabeth Helen',	'Blackburn',	'Molecular Biologist', '{"Biology"}', '{"Medicine"}', 'https://en.wikipedia.org/wiki/Elizabeth_Blackburn', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Elizabeth_Blackburn_CHF_Heritage_Day_2012_Rush_001.JPG/250px-Elizabeth_Blackburn_CHF_Heritage_Day_2012_Rush_001.JPG'),
      ('Susan Jocelyn',	'Bell Burnell',	'Astrophysicist',	'{"Physics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Jocelyn_Bell_Burnell',	'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Launch_of_IYA_2009%2C_Paris_-_Grygar%2C_Bell_Burnell_cropped.jpg/220px-Launch_of_IYA_2009%2C_Paris_-_Grygar%2C_Bell_Burnell_cropped.jpg'),
      ('Jane',	'Morris Goodall',	'Anthropologist and Primatologist',	'{"Biology"}', '{"Environmental preservation"}',	'https://en.wikipedia.org/wiki/Jane_Goodall', 'https://themuslimtimesdotinfodotcom.files.wordpress.com/2019/09/jane-goodall.jpg?w=667'),
      ('Virginia',	'H. Holsinger',	'Chemistry and Food Science',	'{"Chemistry"}',	'{"Food Accesibility", "Chemistry"}',	'https://en.wikipedia.org/wiki/Virginia_Holsinger',	'https://cen.acs.org/content/dam/cen/87/41/8741obits_3.jpg'),
      ('Rachel',	'Louise Carson',	 'Marine Biologist, Conservationist, and Author', '{"Biology"}', '{"Environmental preservation"}',	'https://en.wikipedia.org/wiki/Rachel_Carson',	'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Rachel-Carson.jpg/220px-Rachel-Carson.jpg'),
      ('Lydia',	'Villa-Komaroff',	'Molecular Biology', '{"Biology"}', '{"Materials development"}',	'https://en.wikipedia.org/wiki/Lydia_Villa-Komaroff',	'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Lydia_Villa-Komaroff-2.jpg/220px-Lydia_Villa-Komaroff-2.jpg'),
      ('Chien-Shiung',	'Wu',	'Experimental Physicist', '{"Physics"}', 	'{"Physics"}', 'https://en.wikipedia.org/wiki/Chien-Shiung_Wu',	'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Chien-Shiung_Wu_%281912-1997%29_in_1958.jpg/220px-Chien-Shiung_Wu_%281912-1997%29_in_1958.jpg'),
      ('Ruth Rogan', 'Benerito',	'Chemist',	'{"Chemistry"}',	'{"Materials development", "Chemistry"}',	'https://en.wikipedia.org/wiki/Ruth_R._Benerito', 'https://upload.wikimedia.org/wikipedia/en/9/95/Ruth_R._Benerito.jpg'),
      ('Lise',	'Meitner',	'Physicist', '{"Physics"}',	'{"Physics"}',	'https://en.wikipedia.org/wiki/Lise_Meitner',	'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Lise_Meitner_%281878-1968%29%2C_lecturing_at_Catholic_University%2C_Washington%2C_D.C.%2C_1946.jpg/220px-Lise_Meitner_%281878-1968%29%2C_lecturing_at_Catholic_University%2C_Washington%2C_D.C.%2C_1946.jpg'),
      ('Marie',	'Skłodowska Curie',	'Physicist and Chemist',	'{"Physics", "Chemistry"}',	'{"Medicine", "Chemistry"}',	'https://en.wikipedia.org/wiki/Marie_Curie',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_c1920.jpg/220px-Marie_Curie_c1920.jpg'),
      ('Rosalind',	'Franklin',	'Chemist and X-Rray Crystallographer',	'{"Chemistry"}',	'{"Medicine", "Chemistry"}',	'https://en.wikipedia.org/wiki/Rosalind_Franklin',	'https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Rosalind_Franklin_%281920-1958%29.jpg/220px-Rosalind_Franklin_%281920-1958%29.jpg'),
      ('Jennifer Anne', 'Doudna',	'Biochemist',	'{"Biology", "Chemistry"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/Jennifer_Doudna',	'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Professor_Jennifer_Doudna_ForMemRS.jpg/220px-Professor_Jennifer_Doudna_ForMemRS.jpg'),
      ('Maria',	'Goeppert Mayer',	'Theoretical Physicist',	'{"Physics"}',	'{"Physics"}',	'https://en.wikipedia.org/wiki/Maria_Goeppert_Mayer',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Maria_Goeppert-Mayer_portrait.jpg/220px-Maria_Goeppert-Mayer_portrait.jpg'),
      ('Lisa',	'Randall',	'Theoretical Physicist',	'{"Physics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Lisa_Randall',	'https://upload.wikimedia.org/wikipedia/commons/8/8a/Lisa-randall-at-ted-cropped.jpg'),
      ('Alice Augusta',	'Ball',	'Chemist',	'{"Chemistry"}', '{"Medicine", "Chemistry"}',	'https://en.wikipedia.org/wiki/Alice_Ball',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Alicia_Augusta_Ball.jpg/220px-Alicia_Augusta_Ball.jpg'),
      ('Williamina Paton',	'Stevens Fleming',	'Astronomer',	'{"Astronomy"}',	'{"Understanding the universe", "Astronomy"}',	'https://en.wikipedia.org/wiki/Williamina_Fleming',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Williamina_Paton_Stevens_Fleming_circa_1890s.jpg/200px-Williamina_Paton_Stevens_Fleming_circa_1890s.jpg'),
      ('Annie',	'Jump Cannon',	'Astronomer',	'{"Astronomy"}', '{"Understanding the universe", "Astronomy"}',	'https://en.wikipedia.org/wiki/Annie_Jump_Cannon',	'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Annie_Jump_Cannon_1922_Portrait.jpg/220px-Annie_Jump_Cannon_1922_Portrait.jpg'),
      ('Isabella',	'Karle',	'Chemist',	'{"Chemistry"}',	'{"Medicine", "Chemistry"}',	'https://en.wikipedia.org/wiki/Isabella_Karle',	'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Isabella-karle-nrl-2009.jpg/220px-Isabella-karle-nrl-2009.jpg'),
      ('Gerty Theresa',	'Cori',	'Biochemist',	'{"Biology", "Chemistry"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/Gerty_Cori',	'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Gerty_Theresa_Cori.jpg/220px-Gerty_Theresa_Cori.jpg'),
      ('Caroline',	'Herschel',	'Astronomer',	'{"Astronomy"}',	'{"Understanding the universe", "Astronomy"}',	'https://en.wikipedia.org/wiki/Caroline_Herschel',	'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/1829_Melchior_Gommar_Tieleman%2C_%C3%96lgem%C3%A4lde_Caroline_Herschel_Hannover.tif/lossy-page1-220px-1829_Melchior_Gommar_Tieleman%2C_%C3%96lgem%C3%A4lde_Caroline_Herschel_Hannover.tif.jpg'),
      ('Annie',	'Scott Dill Maunder',	'Astronomer',	'{"Astronomy"}',	'{"Understanding the universe", "Astronomy"}',	'https://en.wikipedia.org/wiki/Annie_S._D._Maunder',	'https://upload.wikimedia.org/wikipedia/commons/f/f6/Annie-Scott-Dill-Maunder-ne-Russell.jpg'),
      ('Sara',	'Seager',	'Astronomer and Planetary Scientist',	'{"Astronomy"}',	'{"Understanding the universe", "Astronomy"}',	'https://en.wikipedia.org/wiki/Sara_Seager',	'https://mediad.publicbroadcasting.net/p/ktep/files/styles/medium/public/201806/seager_sara.jpg'),
      ('Mary Lucy',	'Cartwright',	'Mathematician',	'{"Mathematics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Mary_Cartwright',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Mary_cartwright.jpg/220px-Mary_cartwright.jpg'),
      ('Amalie',	'Emmy Noether',	'Mathematician',	'{"Mathematics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Emmy_Noether',	'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Noether.jpg/220px-Noether.jpg'),
      ('Sofya',	'Vasilyevna Kovalevskaya',	'Mathematician',	'{"Mathematics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Sofya_Kovalevskaya',	'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Sofja_Wassiljewna_Kowalewskaja_1.jpg/220px-Sofja_Wassiljewna_Kowalewskaja_1.jpg'),
      ('Augusta Ada',	'Lovelace',	'Mathematician and Writer',	'{"Mathematics"}',	'{"New technologies"}',	'https://en.wikipedia.org/wiki/Ada_Lovelace', 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Ada_Byron_daguerreotype_by_Antoine_Claudet_1843_or_1850.jpg'),
      ('Grace',	'Hopper',	'Computer Scientist',	'{"Computer Science"}',	'{"New technologies"}',	'https://en.wikipedia.org/wiki/Grace_Hopper', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg/220px-Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg'),
      ('Gladys',	'Mae West',	'Mathematician',	'{"Mathematics"}',	'{"New technologies"}',	'https://en.wikipedia.org/wiki/Gladys_West',	'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Dr_Gladys_West_Hall_of_Fame.jpg/220px-Dr_Gladys_West_Hall_of_Fame.jpg'),
      ('Maryam',	'Mirzakhani',	'Mathematician',	'{"Mathematics"}',	'{"Planetary Science"}',	'https://en.wikipedia.org/wiki/Maryam_Mirzakhani',	'https://upload.wikimedia.org/wikipedia/commons/b/b1/Maryam_Mirzakhani_in_Seoul_2014.jpg'),
      ('Karen',	'Keskulla Uhlenbeck',	'Mathematician',	'{"Mathematics"}', '{"Physics"}',	'https://en.wikipedia.org/wiki/Karen_Uhlenbeck',	'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Uhlenbeck_Karen_1982_%28cropped%29.jpg/220px-Uhlenbeck_Karen_1982_%28cropped%29.jpg'),
      ('Ingrid',	'Daubechies',	'Physicist and Mathematician',	'{"Mathematics", "Physics"}',	'{"New technologies"}',	'https://en.wikipedia.org/wiki/Ingrid_Daubechies',	'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ingrid_Daubechies_%282005%29.jpg/220px-Ingrid_Daubechies_%282005%29.jpg'),
      ('Ada E.',	'Yonath',	'Crystallographer',	'{"Chemistry"}', '{"Medicine", "Chemistry"}', 'https://en.wikipedia.org/wiki/Ada_Yonath',	'https://www.lindau-nobel.org/wp-content/uploads/2015/03/Yonath-e1426590932177.jpg'),
      ('Hedy',	'Lamarr',	'Inventor, Actress, and Film Producer - Radio Signals',	'{"Engineering"}',	'{"New technologies"}',	'https://en.wikipedia.org/wiki/Hedy_Lamarr',	'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Hedy_Lamarr_in_The_Heavenly_Body_1944.jpg/220px-Hedy_Lamarr_in_The_Heavenly_Body_1944.jpg'),
      ('Tu',	'Youyou',	'Malariologist and Pharmaceutical Chemist',	'{"Chemistry",  "Medicine"}',	'{"Medicine", "Chemistry"}', 'https://en.wikipedia.org/wiki/Tu_Youyou',	'https://lh3.googleusercontent.com/proxy/f50p-ZkXcz1OoOBGVTTf-eIUJdM67jSGhR08GGp65_16Lai3B8UGCZ1SL9purrI_WJKADXhS-sdSsskgajO-7KKSYIr38la0Zf--8N-XgjpsFIVikKk'),
      ('Rita', 'Levi-Montalcini',	'Neurobiologist',	'{"Neurobiology"}', '{"Medicine"}',	'https://en.wikipedia.org/wiki/Rita_Levi-Montalcini',	'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Rita_Levi-Montalcini_bandw.jpg/220px-Rita_Levi-Montalcini_bandw.jpg'),
      ('Gertrude Belle',	'Elion',	'Pharmacologist and Biochemist', '{"Biology", "Chemistry",  "Medicine"}',	'{"Medicine", "Chemistry"}', 'https://en.wikipedia.org/wiki/Gertrude_B._Elion',	'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Gertrude_Elion.jpg/220px-Gertrude_Elion.jpg'),
      ('Dorothy Mary',	'Crowfoot Hodgkin',	 'Chemist',  '{"Biology", "Chemistry",  "Medicine"}',	'{"Medicine", "Chemistry"}', 'https://en.wikipedia.org/wiki/Dorothy_Hodgkin',	'https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Dorothy_Hodgkin_Nobel.jpg/220px-Dorothy_Hodgkin_Nobel.jpg'),
      ('Barbara',	'McClintock',	'Cytogeneticist',	'{"Medicine"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/Barbara_McClintock',	'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Barbara_McClintock_%281902-1992%29_shown_in_her_laboratory_in_1947.jpg/220px-Barbara_McClintock_%281902-1992%29_shown_in_her_laboratory_in_1947.jpg'),
      ('Mary', 'Engle Pennington',	'Refrigeration Engineer and Bacteriological Chemist',	'{"Chemistry",  "Engineering"}',	'{"Food Accesibility", "Chemistry", "New technologies"}',	'https://en.wikipedia.org/wiki/Mary_Engle_Pennington',	'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Mary_Engle_Pennington_%281872-1952%29.jpg/220px-Mary_Engle_Pennington_%281872-1952%29.jpg'),
      ('Virginia',	'Apgar',	'Obstetrical Anesthesiologist',	'{"Chemistry",  "Medicine"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/Virginia_Apgar',	'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Virginia-Apgar-July-6-1959.jpg/220px-Virginia-Apgar-July-6-1959.jpg'),
      ('May-Britt',	'Moser',	'Neuroscientist and Psychologist',	'{"Medicine", "Neurobiology"}', '{"Medicine"}',	'https://en.wikipedia.org/wiki/May-Britt_Moser', 'https://www.nobelprize.org/images/may-britt-moser-15191-portrait-medium.jpg'),
      ('Françoise',	'Barré-Sinoussi',	'Virologist',	'{"Medicine", "Biology"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/May-Britt_Moser',	'https://www.nobelprize.org/images/may-britt-moser-15191-portrait-medium.jpg'),
      ('Frances',	'Hamilton Arnold',	'Chemical Engineer',	'{"Chemistry", "Engineering"}',	'{"Medicine", "Alternative energies"}',	'https://en.wikipedia.org/wiki/Frances_Arnold',	'https://www.mediatheque.lindau-nobel.org/Content/Assets/Medium/38459___arnold_frances_h_chemistry.jpg'),
      ('Valentina',	'Vladimirovna Tereshkova',	'Engineer and Former Cosmonaut',	'{"Engineering"}',	'{"Planetary Science"}',	'https://en.wikipedia.org/wiki/Valentina_Tereshkova',	'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Valentina_Tereshkova_%28January_1963%29.jpg/170px-Valentina_Tereshkova_%28January_1963%29.jpg'),
      ('Brenda',	'Milner',	'Neuropsychologist',	'{"Medicine", "Neurobiology"}',	'{"Medicine"}',	'https://en.wikipedia.org/wiki/Brenda_Milner',	'https://www.balzan.org/upload/qtasccrbvnb42mm2a1qzl4ce201302201624Milner.jpg'),
      ('Katherine',	'Johnson',	'Mathematician',	'{"Mathematics"}',	'{"Planetary Science"}',	'https://en.wikipedia.org/wiki/Katherine_Johnson',	'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Katherine_Johnson_1983.jpg/220px-Katherine_Johnson_1983.jpg'),
      ('Mary', 	'Jackson',	'Mathematician and Aerospace Engineer',	'{"Engineering"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Mary_Jackson_(engineer)',	'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Mary_Jackson_1979_Portrait_%28LRC-1979-B701_P-07085%29.jpg/220px-Mary_Jackson_1979_Portrait_%28LRC-1979-B701_P-07085%29.jpg'),
      ('Dorothy', 	'Vaughan',	'Mathematician',	'{"Mathematics"}',	'{"Understanding the universe"}',	'https://en.wikipedia.org/wiki/Dorothy_Vaughan',	'https://cdn.shopify.com/s/files/1/0181/1347/files/doroth_vaughan_nasa_2_resize_md.jpg?v=1576107375'),
      ('Claudia', 	'Alexander',	'Planetary Scientist',	'{"Geology"}',	'{"Planetary Science"}', 'https://en.wikipedia.org/wiki/Claudia_Alexander',	'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Claudia_Alexander.jpg/230px-Claudia_Alexander.jpg')
      RETURNING *;`
      ;
  
    try {
        const {rows} = await db.query(scientistsQuery);
    res.status(201).json(rows)
    } catch (e) {
      console.log({ scientistSeedError: e.message });
    }
  
  };

  module.exports.scientistHasProgram = async (req, res, next) => {
    //Questions query
    const shpQuery = `
      INSERT INTO scientist_has_program (scientist_id, program_id) VALUES
      (1, 8),
      (1,	9),
(1,	10),
(1,	11),
(1,	29),
(1,	38),
(1,	39),
(1,	48),
(1,	49),
(1,	54),
(1,	69),
(1,	73),
(1,	81),
(1,	82),
(1,	87),
(1,	100),
(1,	101),
(1,	104),
(1,	127),
(1,	137),
(2,	1),
(2,	12),
(2,	13),
(2,	14),
(2,	42),
(2,	47),
(2,	52),
(2,	63),
(2,	64),
(2,	74),
(2,	83),
(2,	93),
(2,	95),
(2,	102),
(2,	105),
(2,	106),
(2,	107),
(2,	110),
(2,	111),
(2,	114),
(2,	125),
(2,	126),
(2,	129),
(2,	130),
(3,	30),
(3,	31),
(3,	43),
(3,	70),
(3,	71),
(3,	72),
(3,	79),
(3,	86),
(3,	90),
(3,	94),
(3,	99),
(3,	113),
(3,	122),
(3,	140),
(3,	141),
(3,	142),
(4,	9),
(4,	10),
(4,	11),
(4,	29),
(4,	38),
(4,	39),
(4,	48),
(4,	49),
(4,	54),
(4,	69),
(4,	73),
(4,	81),
(4,	82),
(4,	87),
(4,	100),
(4,	101),
(4,	104),
(4,	127),
(4,	137),
(5,	9),
(5,	10),
(5,	11),
(5,	29),
(5,	38),
(5,	39),
(5,	48),
(5,	49),
(5,	54),
(5,	69),
(5,	73),
(5,	81),
(5,	82),
(5,	87),
(5,	100),
(5,	101),
(5,	104),
(5,	127),
(5,	137),
(6,	9),
(6,	10),
(6,	11),
(6,	29),
(6,	38),
(6,	39),
(6,	48),
(6,	49),
(6,	54),
(6,	69),
(6,	73),
(6,	81),
(6,	82),
(6,	87),
(6,	100),
(6,	101),
(6,	104),
(6,	127),
(6,	137),
(7,	30),
(7,	31),
(7,	43),
(7,	70),
(7,	71),
(7,	72),
(7,	79),
(7,	86),
(7,	90),
(7,	94),
(7,	99),
(7,	113),
(7,	122),
(7,	140),
(7,	141),
(7,	142),
(8,	9),
(8,	10),
(8,	11),
(8,	29),
(8,	38),
(8,	39),
(8,	48),
(8,	49),
(8,	54),
(8,	69),
(8,	73),
(8,	81),
(8,	82),
(8,	87),
(8,	100),
(8,	101),
(8,	104),
(8,	127),
(8,	137),
(9,	1),
(9,	12),
(9,	13),
(9,	14),
(9,	42),
(9,	47),
(9,	52),
(9,	63),
(9,	64),
(9,	74),
(9,	83),
(9,	93),
(9,	95),
(9,	102),
(9,	105),
(9,	106),
(9,	107),
(9,	110),
(9,	111),
(9,	114),
(9,	125),
(9,	126),
(9,	129),
(9,	130),
(10,	9),
(10,	10),
(10,	11),
(10,	29),
(10,	38),
(10,	39),
(10,	48),
(10,	49),
(10,	54),
(10,	69),
(10,	73),
(10,	81),
(10,	82),
(10,	87),
(10,	100),
(10,	101),
(10,	104),
(10,	127),
(10,	137),
(11,	9),
(11,	10),
(11,	11),
(11,	29),
(11,	38),
(11,	39),
(11,	48),
(11,	49),
(11,	54),
(11,	69),
(11,	73),
(11,	81),
(11,	82),
(11,	87),
(11,	100),
(11,	101),
(11,	104),
(11,	127),
(11,	137),
(12,	30),
(12,	31),
(12,	43),
(12,	70),
(12,	71),
(12,	72),
(12,	79),
(12,	86),
(12,	90),
(12,	94),
(12,	99),
(12,	113),
(12,	122),
(12,	140),
(12,	141),
(12,	142),
(13,	1),
(13,	12),
(13,	13),
(13,	14),
(13,	42),
(13,	47),
(13,	52),
(13,	63),
(13,	64),
(13,	74),
(13,	83),
(13,	93),
(13,	95),
(13,	102),
(13,	105),
(13,	106),
(13,	107),
(13,	110),
(13,	111),
(13,	114),
(13,	125),
(13,	126),
(13,	129),
(13,	130),
(14,	30),
(14,	31),
(14,	43),
(14,	70),
(14,	71),
(14,	72),
(14,	79),
(14,	86),
(14,	90),
(14,	94),
(14,	99),
(14,	113),
(14,	122),
(14,	140),
(14,	141),
(14,	142),
(15,	30),
(15,	31),
(15,	43),
(15,	70),
(15,	71),
(15,	72),
(15,	79),
(15,	86),
(15,	90),
(15,	94),
(15,	99),
(15,	113),
(15,	122),
(15,	140),
(15,	141),
(15,	142),
(15,	1),
(15,	12),
(15,	13),
(15,	14),
(15,	42),
(15,	47),
(15,	52),
(15,	63),
(15,	64),
(15,	74),
(15,	83),
(15,	93),
(15,	95),
(15,	102),
(15,	105),
(15,	106),
(15,	107),
(15,	110),
(15,	111),
(15,	114),
(15,	125),
(15,	126),
(15,	129),
(15,	130),
(16,	1),
(16,	12),
(16,	13),
(16,	14),
(16,	42),
(16,	47),
(16,	52),
(16,	63),
(16,	64),
(16,	74),
(16,	83),
(16,	93),
(16,	95),
(16,	102),
(16,	105),
(16,	106),
(16,	107),
(16,	110),
(16,	111),
(16,	114),
(16,	125),
(16,	126),
(16,	129),
(16,	130),
(17, 	1),
(17, 	12),
(17, 	13),
(17, 	14),
(17, 	42),
(17, 	47),
(17, 	52),
(17, 	63),
(17, 	64),
(17, 	74),
(17, 	83),
(17, 	93),
(17, 	95),
(17, 	102),
(17, 	105),
(17, 	106),
(17, 	107),
(17, 	110),
(17, 	111),
(17, 	114),
(17, 	125),
(17, 	126),
(17, 	129),
(17, 	130),
(17, 	9),
(17, 	10),
(17, 	11),
(17, 	29),
(17, 	38),
(17, 	39),
(17, 	48),
(17, 	49),
(17, 	54),
(17, 	69),
(17, 	73),
(17, 	81),
(17, 	82),
(17, 	87),
(17, 	100),
(17, 	101),
(17, 	104),
(17, 	127),
(17, 	137),
(18,	30),
(18,	31),
(18,	43),
(18,	70),
(18,	71),
(18,	72),
(18,	79),
(18,	86),
(18,	90),
(18,	94),
(18,	99),
(18,	113),
(18,	122),
(18,	140),
(18,	141),
(18,	142),
(19,	30),
(19,	31),
(19,	43),
(19,	70),
(19,	71),
(19,	72),
(19,	79),
(19,	86),
(19,	90),
(19,	94),
(19,	99),
(19,	113),
(19,	122),
(19,	140),
(19,	141),
(19,	142),
(20,	1),
(20,	12),
(20,	13),
(20,	14),
(20,	42),
(20,	47),
(20,	52),
(20,	63),
(20,	64),
(20,	74),
(20,	83),
(20,	93),
(20,	95),
(20,	102),
(20,	105),
(20,	106),
(20,	107),
(20,	110),
(20,	111),
(20,	114),
(20,	125),
(20,	126),
(20,	129),
(20,	130),
(21,	62),
(21,	80),
(21,	147),
(22,	62),
(22,	80),
(22,	147),
(23, 	1),
(23, 	12),
(23, 	13),
(23, 	14),
(23, 	42),
(23, 	47),
(23, 	52),
(23, 	63),
(23, 	64),
(23, 	74),
(23, 	83),
(23, 	93),
(23, 	95),
(23, 	102),
(23, 	105),
(23, 	106),
(23, 	107),
(23, 	110),
(23, 	111),
(23, 	114),
(23, 	125),
(23, 	126),
(23, 	129),
(23, 	130),
(24, 	1),
(24, 	12),
(24, 	13),
(24, 	14),
(24, 	42),
(24, 	47),
(24, 	52),
(24, 	63),
(24, 	64),
(24, 	74),
(24, 	83),
(24, 	93),
(24, 	95),
(24, 	102),
(24, 	105),
(24, 	106),
(24, 	107),
(24, 	110),
(24, 	111),
(24, 	114),
(24, 	125),
(24, 	126),
(24, 	129),
(24, 	130),
(24, 	9),
(24, 	10),
(24, 	11),
(24, 	29),
(24, 	38),
(24, 	39),
(24, 	48),
(24, 	49),
(24, 	54),
(24, 	69),
(24, 	73),
(24, 	81),
(24, 	82),
(24, 	87),
(24, 	100),
(24, 	101),
(24, 	104),
(24, 	127),
(24, 	137),
(25, 	62),
(25, 	80),
(25, 	147),
(26,	62),
(26,	80),
(26,	147),
(27, 	62),
(27, 	80),
(27, 	147),
(28,	5),
(28,	25),
(28,	41),
(28,	60),
(28,	61),
(28,	78),
(28,	89),
(28,	98),
(28,	112),
(28,	119),
(28,	134),
(28,	136),
(29,	5),
(29,	25),
(29,	41),
(29,	60),
(29,	61),
(29,	78),
(29,	89),
(29,	98),
(29,	112),
(29,	119),
(29,	134),
(29,	136),
(30,	5),
(30,	25),
(30,	41),
(30,	60),
(30,	61),
(30,	78),
(30,	89),
(30,	98),
(30,	112),
(30,	119),
(30,	134),
(30,	136),
(31,	5),
(31,	25),
(31,	41),
(31,	60),
(31,	61),
(31,	78),
(31,	89),
(31,	98),
(31,	112),
(31,	119),
(31,	134),
(31,	136),
(32,	5),
(32,	25),
(32,	41),
(32,	60),
(32,	61),
(32,	78),
(32,	89),
(32,	98),
(32,	112),
(32,	119),
(32,	134),
(32,	136),
(33,	5),
(33,	25),
(33,	41),
(33,	60),
(33,	61),
(33,	78),
(33,	89),
(33,	98),
(33,	112),
(33,	119),
(33,	134),
(33,	136),
(34,	5),
(34,	25),
(34,	41),
(34,	60),
(34,	61),
(34,	78),
(34,	89),
(34,	98),
(34,	112),
(34,	119),
(34,	134),
(34,	136),
(35,	2),
(35,	15),
(35,	16),
(35,	35),
(35,	40),
(35,	53),
(35,	77),
(35,	88),
(35,	96),
(35,	115),
(35,	132),
(35,	133),
(35,	135),
(36, 	5),
(36, 	25),
(36, 	41),
(36, 	60),
(36, 	61),
(36, 	78),
(36, 	89),
(36, 	98),
(36, 	112),
(36, 	119),
(36, 	134),
(36, 	136),
(37,	5),
(37,	25),
(37,	41),
(37,	60),
(37,	61),
(37,	78),
(37,	89),
(37,	98),
(37,	112),
(37,	119),
(37,	134),
(37,	136),
(37,	30),
(37,	31),
(37,	43),
(37,	70),
(37,	71),
(37,	72),
(37,	79),
(37,	86),
(37,	90),
(37,	94),
(37,	99),
(37,	113),
(37,	122),
(37,	140),
(37,	141),
(37,	142),
(38,	3),
(38,	4),
(38,	6),
(38,	7),
(38,	8),
(38,	17),
(38,	20),
(38,	26),
(38,	34),
(38,	36),
(38,	55),
(38,	56),
(38,	57),
(38,	58),
(38,	59),
(38,	75),
(38,	97),
(38,	108),
(38,	109),
(38,	116),
(38,	120),
(38,	121),
(38,	123),
(38,	124),
(38,	131),
(39, 	1),
(39, 	12),
(39, 	13),
(39, 	14),
(39, 	42),
(39, 	47),
(39, 	52),
(39, 	63),
(39, 	64),
(39, 	74),
(39, 	83),
(39, 	93),
(39, 	95),
(39, 	102),
(39, 	105),
(39, 	106),
(39, 	107),
(39, 	110),
(39, 	111),
(39, 	114),
(39, 	125),
(39, 	126),
(39, 	129),
(39, 	130),
(39, 	27),
(39, 	28),
(39, 	46),
(39, 	50),
(40,	51),
(40,	92),
(40,	138),
(40,	139),
(41,	9),
(41,	10),
(41,	11),
(41,	29),
(41,	38),
(41,	39),
(41,	48),
(41,	49),
(41,	54),
(41,	69),
(41,	73),
(41,	81),
(41,	82),
(41,	87),
(41,	100),
(41,	101),
(41,	104),
(41,	127),
(41,	137),
(41,	1),
(41,	12),
(41,	13),
(41,	14),
(41,	42),
(41,	47),
(41,	52),
(41,	63),
(41,	64),
(41,	74),
(41,	83),
(41,	93),
(41,	95),
(41,	102),
(41,	105),
(41,	106),
(41,	107),
(41,	110),
(41,	111),
(41,	114),
(41,	125),
(41,	126),
(41,	129),
(41,	130),
(41,	27),
(41,	28),
(41,	46),
(41,	50),
(42,	9),
(42,	10),
(42,	11),
(42,	29),
(42,	38),
(42,	39),
(42,	48),
(42,	49),
(42,	54),
(42,	69),
(42,	73),
(42,	81),
(42,	82),
(42,	87),
(42,	100),
(42,	101),
(42,	104),
(42,	127),
(42,	137),
(42,	1),
(42,	12),
(42,	13),
(42,	14),
(42,	42),
(42,	47),
(42,	52),
(42,	63),
(42,	64),
(42,	74),
(42,	83),
(42,	93),
(42,	95),
(42,	102),
(42,	105),
(42,	106),
(42,	107),
(42,	110),
(42,	111),
(42,	114),
(42,	125),
(42,	126),
(42,	129),
(42,	130),
(42,	27),
(42,	28),
(42,	46),
(42,	50),
(43,	27),
(43,	28),
(43,	46),
(43,	50),
(44,	1),
(44,	12),
(44,	13),
(44,	14),
(44,	42),
(44,	47),
(44,	52),
(44,	63),
(44,	64),
(44,	74),
(44,	83),
(44,	93),
(44,	95),
(44,	102),
(44,	105),
(44,	106),
(44,	107),
(44,	110),
(44,	111),
(44,	114),
(44,	125),
(44,	126),
(44,	129),
(44,	130),
(44,	3),
(44,	4),
(44,	6),
(44,	7),
(44,	8),
(44,	17),
(44,	20),
(44,	26),
(44,	34),
(44,	36),
(44,	55),
(44,	56),
(44,	57),
(44,	58),
(44,	59),
(44,	75),
(44,	97),
(44,	108),
(44,	109),
(44,	116),
(44,	120),
(44,	121),
(44,	123),
(44,	124),
(44,	131),
(45,	1),
(45,	12),
(45,	13),
(45,	14),
(45,	42),
(45,	47),
(45,	52),
(45,	63),
(45,	64),
(45,	74),
(45,	83),
(45,	93),
(45,	95),
(45,	102),
(45,	105),
(45,	106),
(45,	107),
(45,	110),
(45,	111),
(45,	114),
(45,	125),
(45,	126),
(45,	129),
(45,	130),
(45,	27),
(45,	28),
(45,	46),
(45,	50),
(46,	27),
(46,	28),
(46,	46),
(46,	50),
(46,	51),
(46,	92),
(46,	138),
(46,	139),
(47,	27),
(47,	28),
(47,	46),
(47,	50),
(47,	9),
(47,	10),
(47,	11),
(47,	29),
(47,	38),
(47,	39),
(47,	48),
(47,	49),
(47,	54),
(47,	69),
(47,	73),
(47,	81),
(47,	82),
(47,	87),
(47,	100),
(47,	101),
(47,	104),
(47,	127),
(47,	137),
(48,	1),
(48,	12),
(48,	13),
(48,	14),
(48,	42),
(48,	47),
(48,	52),
(48,	63),
(48,	64),
(48,	74),
(48,	83),
(48,	93),
(48,	95),
(48,	102),
(48,	105),
(48,	106),
(48,	107),
(48,	110),
(48,	111),
(48,	114),
(48,	125),
(48,	126),
(48,	129),
(48,	130),
(49,	1),
(49,	12),
(49,	13),
(49,	14),
(49,	42),
(49,	47),
(49,	52),
(49,	63),
(49,	64),
(49,	74),
(49,	83),
(49,	93),
(49,	95),
(49,	102),
(49,	105),
(49,	106),
(49,	107),
(49,	110),
(49,	111),
(49,	114),
(49,	125),
(49,	126),
(49,	129),
(49,	130),
(49,	3),
(49,	4),
(49,	6),
(49,	7),
(49,	8),
(49,	17),
(49,	20),
(49,	26),
(49,	34),
(49,	36),
(49,	55),
(49,	56),
(49,	57),
(49,	58),
(49,	59),
(49,	75),
(49,	97),
(49,	108),
(49,	109),
(49,	116),
(49,	120),
(49,	121),
(49,	123),
(49,	124),
(49,	131),
(50,	3),
(50,	4),
(50,	6),
(50,	7),
(50,	8),
(50,	17),
(50,	20),
(50,	26),
(50,	34),
(50,	36),
(50,	55),
(50,	56),
(50,	57),
(50,	58),
(50,	59),
(50,	75),
(50,	97),
(50,	108),
(50,	109),
(50,	116),
(50,	120),
(50,	121),
(50,	123),
(50,	124),
(50,	131),
(51,	27),
(51,	28),
(51,	46),
(51,	50),
(51,	51),
(51,	92),
(51,	138),
(51,	139),
(52,	5),
(52,	25),
(52,	41),
(52,	60),
(52,	61),
(52,	78),
(52,	89),
(52,	98),
(52,	112),
(52,	119),
(52,	134),
(52,	136),
(53,	3),
(53,	4),
(53,	6),
(53,	7),
(53,	8),
(53,	17),
(53,	20),
(53,	26),
(53,	34),
(53,	36),
(53,	55),
(53,	56),
(53,	57),
(53,	58),
(53,	59),
(53,	75),
(53,	97),
(53,	108),
(53,	109),
(53,	116),
(53,	120),
(53,	121),
(53,	123),
(53,	124),
(53,	131),
(54,	5),
(54,	25),
(54,	41),
(54,	60),
(54,	61),
(54,	78),
(54,	89),
(54,	98),
(54,	112),
(54,	119),
(54,	134),
(54,	136),
(55,	18),
(55,	21),
(55,	22),
(55,	33),
(55,	45),
(55,	65),
(55,	67),
(55,	68),
(55,	76),
(55,	91),
(55,	146)      
      RETURNING *;
  `;
    try {
      const {rows} = await db.query(shpQuery);
      res.status(201).json(rows)
  } 
    catch (e) {
      console.log({ shpQuerySeedError: e.message });
    }
  };

  module.exports.seedPart3 = async (req, res, next) => {
    // university Programs query
   const uniprogramsQuery = `INSERT INTO university_program (program_name, university_name, duration, program_site, country, city, field) VALUES
   ('Chemical Engineer', 'University of Cambridge', '3 years',  'https://www.undergraduate.study.cam.ac.uk/courses/chemical-engineering', 'United Kingdom', 'Cambridge', '{"Chemistry"}'), 
   ('Chemical Engineer', 'University of Cambridge', '3 years',  'https://www.undergraduate.study.cam.ac.uk/courses/computer-science', 'United Kingdom', 'Cambridge', '{"Computer science"}'),  
   ('Engineering', 'University of Cambridge',  '3 years',  'https://www.undergraduate.study.cam.ac.uk/courses/engineering', 'United Kingdom', 'Cambridge', '{"Engineering"}'), 
   ('Manufacturing Engineering', 'University of Cambridge', '3 years',  'https://www.undergraduate.study.cam.ac.uk/courses/manufacturing-engineering', 'United Kingdom', 'Cambridge', '{"Engineering"}'), 
   ('Mathematics', 'University of Cambridge', '3 years', 'https://www.undergraduate.study.cam.ac.uk/courses/mathematics', 'United Kingdom', 'Cambridge', '{"Mathematics"}'), 
   ('Aeronautical Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/aeronautics-department/aeronautical-engineering/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Aeronautics with Spacecraft Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/aeronautics-department/aeronautics-spacecraft-engineering/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Biochemistry', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/life-sciences-department/biochemistry-bsc/', 'United Kingdom', 'London', '{"Engineering", "Biology"}'), 
   ('Biological Sciences', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/life-sciences-department/biological-sciences-bsc/', 'United Kingdom', 'London', '{"Biology"}'), 
   ('Biomedical Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/bioengineering-department/biomedical-engineering-meng/', 'United Kingdom', 'London', '{"Biology", "Engineering"}'), 
   ('Biotechnology', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/life-sciences-department/biotechnology-bsc/', 'United Kingdom', 'London', '{"Biology"}'), 
   ('Chemical Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/chemical-engineering-department/chemical-engineering/', 'United Kingdom', 'London', '{"Chemistry", "Engineering"}'), 
   ('Chemistry', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/chemistry-department/chemistry-bsc/', 'United Kingdom', 'London', '{"Chemistry"}'), 
   ('Chemistry with Molecular Physics', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/chemistry-department/chemistry-molecular-physics-msci/', 'United Kingdom', 'London', '{"Chemistry", "Physics"}'), 
   ('Computing', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/computing-department/computing-beng/', 'United Kingdom', 'London', '{"Computer science"}'), 
   ('Computing (Artificial Intelligence and Machine Learning)', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/computing-department/meng-computing-artificial-intelligence/', 'United Kingdom', 'London', '{"Computer science"}'), 
   ('Design Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/school-design-engineering/design-engineering/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Earth and Planetary Science', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/earth-science-department/planetary-science-bsc/', 'United Kingdom', 'London', '{"Planetary Science"}'), 
   ('Ecology and Environmental Biology', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/life-sciences-department/ecology-and-environmental-biology-bsc/', 'United Kingdom', 'London', '{"Enviromental Science", "Biology"}'), 
   ('Electrical and Electronic Engineering', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/electrical-engineering-department/electrical-and-electronic-engineering-beng/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Geology', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/earth-science-department/geology-bsc/', 'United Kingdom', 'London', '{"Planetary Science"}'), 
   ('Geophysics', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/earth-science-department/geophysics-bsc/', 'United Kingdom', 'London', '{"Planetary Science"}'), 
   ('Materials Science and Engineering', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/materials-department/materials-science-and-engineering-beng/', 'United Kingdom', 'London', '{"Materials Science", "Engineering"}'), 
   ('Materials with Nuclear Engineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/materials-department/materials-with-nuclear-engineering-meng/', 'United Kingdom', 'London', '{"Materials Science", "Physics"}'), 
   ('Mathematics', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/mathematics-department/mathematics-bsc/', 'United Kingdom', 'London', '{"Mathematics"}'), 
   ('Mechanical Engineering', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/mechanical-engineering-department/mechanical-engineering-meng/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Medical Biosciences', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/biomedical-science/medical-biosciences/', 'United Kingdom', 'London', '{"Medicine", "Biology"}'), 
   ('Medicine', 'Imperial College London', '6 years', 'https://www.imperial.ac.uk/study/ug/courses/school-of-medicine/medicine/', 'United Kingdom', 'London', '{"Medicine"}'), 
   ('Microbiology', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/life-sciences-department/microbiology-bsc/', 'United Kingdom', 'London', '{"Biology"}'), 
   ('Molecular Bioengineering', 'Imperial College London', '4 years', 'https://www.imperial.ac.uk/study/ug/courses/bioengineering-department/molecular-bioengineering-meng/', 'United Kingdom', 'London', '{"Physics", "Engineering"}'), 
   ('Physics', 'Imperial College London', '3 years', 'https://www.imperial.ac.uk/study/ug/courses/physics-department/physics-bsc/', 'United Kingdom', 'London', '{"Physics"}'), 
   ('Environmental Engineering', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/architecture-and-civil-engineering/environmental-engineering.html', 'Switzerland', 'Zurich', '{"Enviromental", "Science	Engineering"}'), 
   ('Geospatial Engineering', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/architecture-and-civil-engineering/geospatial-engineering.html', 'Switzerland', 'Zurich', '{"Planetary Science", "Engineering"}'), 
   ('Electrical Engineering and Information Technology', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/engineering-sciences/electrical-engineering-and-information-technology.html', 'Switzerland', 'Zurich', '{"Engineering"}'), 
   ('Computer Science (German)', 'ETH Zurich', '3 years', 'https://ethz.ch/de/studium/bachelor/studienangebot/ingenieurwissenschaften/informatik.html', 'Switzerland', 'Zurich', '{"Computer science"}'), 
   ('Mechanical Engineering', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/engineering-sciences/mechanical-engineering.html', 'Switzerland', 'Zurich', '{"Engineering"}'), 
   ('Materials Science', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/engineering-sciences/materials-science.html', 'Switzerland', 'Zurich', '{"Materials Science"}'), 
   ('Biology', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/biology.html', 'Switzerland', 'Zurich', '{"Biology"}'), 
   ('Biochemistry – Chemical Biology', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/Biochemie_ChemischeBiologie.html', 'Switzerland', 'Zurich', '{"Biology", "Chemistry"}'), 
   ('Computational Science and Engineering', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/computational-science-and-engineering.html', 'Switzerland', 'Zurich', '{"Computer science"}'), 
   ('Mathematics', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/mathematics.html', 'Switzerland', 'Zurich', '{"Mathematics"}'), 
   ('Pharmaceutical Sciences', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/pharmaceutical-sciences.html', 'Switzerland', 'Zurich', '{"Chemistry", "Biology"}'), 
   ('Physics', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/natural-sciences-and-mathematics/physics.html', 'Switzerland', 'Zurich', '{"Physics"}'), 
   ('Food Science', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/system-oriented-natural-sciences/food-science.html', 'Switzerland', 'Zurich', '{"Food Science"}'), 
   ('Earth Science', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/system-oriented-natural-sciences/earth-sciences.html', 'Switzerland', 'Zurich', '{"Planetary Science"}'), 
   ('Health Sciences and Technology', 'ETH Zurich', '3 years', 'https://ethz.ch/en/studies/prospective-bachelors-degree-students/bachelors-degree-programmes/system-oriented-natural-sciences/health-sciences-and-technology.html', 'Switzerland', 'Zurich', '{"Medicine", "Engineering"}'), 
   ('Biochemistry BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/biochemistry-bsc/', 'United Kingdom', 'London', '{"Chemistry", "Biology"}'), 
   ('Biological Sciences BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/biological-sciences-bsc/', 'United Kingdom', 'London', '{"Biology"}'), 
   ('Biomedical Sciences BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/biomedical-sciences-bsc/', 'United Kingdom', 'London', '{"Biology", "Medicine"}'), 
   ('Infection and Immunity BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/infection-immunity-bsc/', 'United Kingdom', 'London', '{"Medicine", "Biology"}'), 
   ('Neuroscience BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/neuroscience-bsc/', 'United Kingdom', 'London', '{"Neurobiology"}'), 
   ('Pharmacology BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/pharmacology-bsc/', 'United Kingdom', 'London', '{"Chemistry", "Biology"}'), 
   ('Computer Science', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/computer-science-bsc/', 'United Kingdom', 'London', '{"Computer science"}'), 
   ('Bioprocessing of New Medicines (Science and Engineering) BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/bioprocessing-new-medicines-science-engineering-bsc/', 'United Kingdom', 'London', '{"Biology", "Engineering"}'), 
   ('Engineering (Biochemical) BEng', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-biochemical-beng/', 'United Kingdom', 'London', '{"Engineering", "Biology"}'), 
   ('Engineering (Biomedical) BEng', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-biomedical-beng/', 'United Kingdom', 'London', '{"Engineering", "Medicine"}'), 
   ('Engineering (Chemical) BEng', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-chemical-beng/', 'United Kingdom', 'London', '{"Engineering", "Chemistry"}'), 
   ('Engineering (Electronic and Electrical) BEng', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-electronic-electrical-beng/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Engineering (Mechanical) BEng', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-mechanical-beng/', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Mathematics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/mathematics-bsc/', 'United Kingdom', 'London', '{"Mathematics"}'), 
   ('Mathematics and Physics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/mathematics-physics-bsc/', 'United Kingdom', 'London', '{"Mathematics", "Physics"}'), 
   ('Astrophysics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/astrophysics-bsc/', 'United Kingdom', 'London', '{"Asthronomy", "Physics"}'), 
   ('Chemistry BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering-chemical-beng/', 'United Kingdom', 'London', '{"Chemistry"}'), 
   ('Chemistry with Mathematics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/chemistry-mathematics-bsc/', 'United Kingdom', 'London', '{"Chemistry", "Mathematics"}'), 
   ('Earth Sciences BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/earth-sciences-bsc/', 'United Kingdom', 'London', '{"Planetary Science"}'), 
   ('Environmental Geoscience BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/environmental-geoscience-bsc/', 'United Kingdom', 'London', '{"Enviromental Science"}'), 
   ('Geology BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/geology-bsc/', 'United Kingdom', 'London', '{"Planetary Science"}'), 
   ('Geophysics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/geophysics-bsc/', 'United Kingdom', 'London', '{"Planetary", "Science	Physics"}'), 
   ('Natural Sciences BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/natural-sciences-bsc/', 'United Kingdom', 'London', '{"Biology", "Chemistry"}'), 
   ('Physics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/physics-bsc/', 'United Kingdom', 'London', '{"Physics"}'), 
   ('Physics with Medical Physics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/physics-medical-physics-bsc/', 'United Kingdom', 'London', '{"Physics", "Engineering"}'), 
   ('Theoretical Physics BSc', 'UCL', '3 years', 'https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/theoretical-physics-bsc/', 'United Kingdom', 'London', '{"Physics"}'), 
   ('Biological Sciences', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=313', 'United Kingdom', 'Edinburgh', '{"Biology"}'), 
   ('Chemistry', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=315', 'United Kingdom', 'Edinburgh', '{"Chemistry"}'), 
   ('Engineering', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=320', 'United Kingdom', 'Edinburgh', '{"Engineering"}'), 
   ('GeoSciences', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=314', 'United Kingdom', 'Edinburgh', '{"Planetary Science"}'), 
   ('Informatics ', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=319', 'United Kingdom', 'Edinburgh', '{"Computer science"}'), 
   ('Mathematics', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=318', 'United Kingdom', 'Edinburgh', '{"Mathematics"}'), 
   ('Physics and Astronomy', 'University of Edinburgh', '4 years', 'https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=search&college=SCE&school=316', 'Germany', 'Munich', '{"Physics", "Asthronomy"}'), 
   ('Astrophysik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/astrophysik/index.html', 'Germany', 'Munich', '{"Asthronomy", "Physics"}'), 
   ('Bioinformatik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/bioinform_/index.html', 'Germany', 'Munich', '{"Biology", "Mathematics"}'), 
   ('Biologie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/biologie/index.html', 'Germany', 'Munich', '{"Biology"}'), 
   ('Chemie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/chemie/index.html', 'Germany', 'Munich', '{"Chemistry"}'), 
   ('Evolution, Ecology and Systematics', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/evolution/index.html', 'Germany', 'Munich', '{"Enviromental Science"}'), 
   ('Geologie/Paläontologie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/geologie__/index.html', 'Germany', 'Munich', '{"Enviromental Science"}'), 
   ('Geophysik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/geophysik/index.html', 'Germany', 'Munich', '{"Physics", "Planetary Science"}'), 
   ('Humanbiologie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/humanbiol_/index.html', 'Germany', 'Munich', '{"Biology"}'), 
   ('Informatik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/informatik/index.html', 'Germany', 'Munich', '{"Computer science"}'), 
   ('Mathematik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/mathematik/index.html', 'Germany', 'Munich', '{"Mathematics"}'), 
   ('Meteorologie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/meteorolo_/index.html', 'Germany', 'Munich', '{"Physics"}'), 
   ('Mineralogie', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/mineralog_/index.html', 'Germany', 'Munich', '{"Planetary Science"}'), 
   ('Neurosciences', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/neuroscience/index.html', 'Germany', 'Munich', '{"Neurobiology"}'), 
   ('Pharmaceutical Sciences', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/pharmaceu_/index.html', 'Germany', 'Munich', '{"Chemistry"}'), 
   ('Physik', 'LMU Munich', '3 years', 'https://www.uni-muenchen.de/studium/studienangebot/studiengaenge/studienfaecher/physik/index.html', 'Germany', 'Munich', '{"Physics"}'), 
   ('Chemistry', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/chemistry', 'United Kingdom', 'London', '{"Chemistry"}'), 
   ('Computer science', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/computer-science', 'United Kingdom', 'London', '{"Computer science"}'), 
   ('Engineering', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/engineering', 'United Kingdom', 'London', '{"Engineering"}'), 
   ('Mathematics', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/mathematics', 'United Kingdom', 'London', '{"Mathematics"}'), 
   ('Physics', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/physics', 'United Kingdom', 'London', '{"Physics"}'), 
   ('Biomedical Sciences', 'King’s College London', '3 years', 'https://www.kcl.ac.uk/study-at-kings/ug/subjects/biomedical-sciences', 'United Kingdom', 'London', '{"Biology", "Engineering"}'), 
   ('Biomedicine', 'Karolinska Institute', '3 years', 'https://education.ki.se/programme/1bi17-bachelors-programme-in-biomedicine', 'Sweden', 'Stockholm', '{"Biology", "Engineering"}'),
   ('Biochemistry', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/biochemie-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Chemistry", "Biology"}'), 
   ('Biogenic Materials', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/biogene-werkstoffe-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Materials Science"}'), 
   ('Bioinformatics', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/bioinformatik-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Biology", "Mathematics"}'), 
   ('chemical Biotechnology', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/chemische-biotechnologie-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Chemistry", "Engineering"}'), 
   ('Chemical Engineering', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/chemical-engineering-bachelor-of-engineering-beng/', 'Germany', 'Munich', '{"Chemistry"}'), 
   ('Chemistry', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/chemie-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Chemistry"}'), 
   ('Electrical Engineering and Information Technology', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/elektrotechnik-und-informationstechnik-bachelor-of-science-bsc/', 'Germany', 'Munich', '{"Engineering", "Computer science"}'), 
   ('Electronics and Data Engineering', 'Technical University of Munich', '3 years', 'https://www.tum.de/en/studies/degree-programs/detail/electronics-data-engineering-bachelor-of-engineering-beng/', 'Germany', 'Munich', '{"Engineering", "Computer science"}'), 
   ('Biochemistry', 'Heidelberg University', '3 years', 'https://www.bio.uni-heidelberg.de/biochemistry', 'Germany', 'Heidelberg', '{"Chemistry"}'), 
   ('Chemie und Geowissenschaften', 'Heidelberg University', '3 years', 'https://www.timeshighereducation.com/world-university-rankings/heidelberg-university', 'Germany', 'Heidelberg', '{"Chemistry"}'), 
   ('Mathematik und Informatik', 'Heidelberg University', '3 years', 'https://www.timeshighereducation.com/world-university-rankings/heidelberg-university', 'Germany', 'Heidelberg', '{"Mathematics", "Computer science"}'), 
   ('Physics and Astronomy', 'Heidelberg University', '3 years', 'https://www.physik.uni-heidelberg.de/?lang=en', 'Germany', 'Heidelberg', '{"Physics", "Asthronomy"}'), 
   ('Chemistry and chemical engineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/chemistry-and-chemical-engineering/', 'Switzerland', 'Lausanne', '{"Chemistry", "Engineering"}'), 
   ('Computer science', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/computer-science/', 'Switzerland', 'Lausanne', '{"Computer science"}'), 
   ('Electrical and electronic engineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/electrical-and-electronic-engineering/', 'Switzerland', 'Lausanne', '{"Engineering"}'), 
   ('Environmental sciences and engineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/environmental-sciences-and-engineering/', 'Switzerland', 'Lausanne', '{"Enviromental Science", "Engineering"}'), 
   ('Materials science and engineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/materials-science-and-engineering/', 'Switzerland', 'Lausanne', '{"Materials Science", "Engineering"}'), 
   ('Mathematics', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/mathematics/', 'Switzerland', 'Lausanne', '{"Mathematics"}'), 
   ('Mechanical engineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/mechanical-engineering/', 'Switzerland', 'Lausanne', '{"Engineering"}'), 
   ('Microengineering', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/microengineering/', 'Switzerland', 'Lausanne', '{"Engineering"}'), 
   ('Physics', 'École Polytechnique Fédérale de Lausanne', '3 years', 'https://www.epfl.ch/education/bachelor/programs/physics/', 'Switzerland', 'Lausanne', '{"Physics"}'), 
   ('Engineering Technology', 'KU Leuven', '3 years', 'https://onderwijsaanbod.kuleuven.be/opleidingen/e/CQ_51601481.htm#activetab=diploma_omschrijving', 'Belgium', 'Leuven', '{"Engineering"}'), 
   ('Aerospace Engineering ', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/03333/beng-aerospace-engineering/', 'United Kingdom', 'Manchester', '{"Engineering"}'), 
   ('Biochemistry', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00521/bsc-biochemistry/', 'United Kingdom', 'Manchester', '{"Chemistry"}'), 
   ('Medical Biochemistry', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00602/bsc-medical-biochemistry/', 'United Kingdom', 'Manchester', '{"Chemistry"}'), 
   ('Earth and Planetary Sciences', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/12106/bsc-earth-and-planetary-sciences/', 'United Kingdom', 'Manchester', '{"Biology"}'), 
   ('Environmental Science', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/12124/bsc-environmental-science/', 'United Kingdom', 'Manchester', '{"Environmental Science"}'), 
   ('Chemical Engineering', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/03340/beng-chemical-engineering/', 'United Kingdom', 'Manchester', '{"Chemistry", "Engineering"}'), 
   ('Chemistry', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00544/bsc-chemistry/', 'United Kingdom', 'Manchester', '{"Chemistry", "Computer science"}'), 
   ('Artificial Intelligence', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00517/bsc-artificial-intelligence/', 'United Kingdom', 'Manchester', '{"Engineering"}'), 
   ('Computer Science', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00560/bsc-computer-science/', 'United Kingdom', 'Manchester', '{"Computer science"}'), 
   ('Software Engineering', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/05125/bsc-software-engineering/', 'United Kingdom', 'Manchester', '{"Computer science"}'), 
   ('Mathematics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00590/bsc-mathematics/', 'United Kingdom', 'Manchester', '{"Mathematics"}'), 
   ('Computer science and Mathematics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00558/bsc-computer-science-and-mathematics/', 'United Kingdom', 'Manchester', '{"Computer science", "Mathematics"}'), 
   ('Mathematics and Physics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00592/bsc-mathematics-and-physics/', 'United Kingdom', 'Manchester', '{"Mathematics", "Physics"}'), 
   ('Molecular Biology', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00614/bsc-molecular-biology/', 'United Kingdom', 'Manchester', '{"Biology"}'), 
   ('Cognitive Neuroscience and Psychology', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00550/bsc-cognitive-neuroscience-and-psychology/', 'United Kingdom', 'Manchester', '{"Neurobiology"}'), 
   ('Neuroscience', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00617/bsc-neuroscience/', 'United Kingdom', 'Manchester', '{"Neurobiology"}'), 
   ('Physics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00638/bsc-physics/', 'United Kingdom', 'Manchester', '{"Physics"}'), 
   ('Physics with Astrophysics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00639/bsc-physics-with-astrophysics/', 'United Kingdom', 'Manchester', '{"Physics", "Asthronomy"}'), 
   ('Physics and Theoretical Physics', 'University of Manchester', '3 years', 'https://www.manchester.ac.uk/study/undergraduate/courses/2021/00642/bsc-physics-with-theoretical-physics/', 'United Kingdom', 'Manchester', '{"Physics"}'), 
   ('Environmental Sciences', 'Wageningen University & Research', '3 years', 'https://www.wur.nl/en/Education-Programmes/Bachelor/bsc-programmes/bsc-environmental-sciences.htm', 'Netherlands', 'Wageningen', '{"Enviromental Science"}'), 
   (' Food Technology', 'Wageningen University & Research', '3 years', 'https://www.wur.nl/en/Education-Programmes/Bachelor/bsc-programmes/bsc-food-technology.htm', 'Netherlands', 'Wageningen', '{"Food Science"}'), 
   ('Animal Sciences', 'Wageningen University & Research', '3 years', 'https://www.wur.nl/en/Education-Programmes/Bachelor/bsc-programmes/bsc-animal-sciences.htm', 'Netherlands', 'Wageningen', '{"Enviromental Science"}'), 
   ('Soil, Water, Atmosphere', 'Wageningen University & Research', '3 years', 'https://www.wur.nl/en/Education-Programmes/Bachelor/bsc-programmes/bsc-soil-water-and-atmosphere.htm', 'Netherlands', 'Wageningen', '{"Planetary Science"}'), 
   ('Astronomy', 'Leiden University', '3 years', 'https://www.universiteitleiden.nl/en/education/study-programmes/bachelor/astronomy', 'Netherlands', 'Leiden', '{"Asthronomy"}') 
   RETURNING *;	
   `;
  
   try {
    
    const {rows} = await db.query(uniprogramsQuery);
res.status(201).json(rows)
    } catch (e) {
      console.log({ uniprogramsSeedError: e.message });
    }
};


// module.exports.seedPart4 = async (req, res, next) => {
//   //Questions query
//   const  scientistHasQuestions= `
//     SELECT * FROM questions JOIN scientist ON scientist.id =  ";
// `;
//   try {
//     const {rows} = await db.query(scientistHasQuestions);
//     res.status(201).json(rows)
// } 
//   catch (e) {
//     console.log({ scientistHasQuestionsError: e.message });
//   }
// };



























